import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Bookmark, ChevronRight, CircleAlert, Crosshair, ExternalLink, Heart, Menu, Search, Shield, Sparkles, Swords, X, Zap } from 'lucide-react';
import { characters, counterMatrix, moves, sources } from './data/content';
import type { Character, MoveCounter } from './data/types';

type View = 'home'|'character'|'fight'|'moves'|'matchup'|'mechanics';
type Level = 'Beginner'|'Intermediate'|'Advanced';
const actionMark: Record<string,string> = {block:'BLK',sideDash:'SD',backDash:'BD',jump:'JMP',evasive:'EVA',interrupt:'INT',counter:'CTR',space:'OUT'};

function App(){
 const [view,setView]=useState<View>('home'); const [enemy,setEnemy]=useState<Character|null>(null); const [player,setPlayer]=useState<Character|null>(null);
 const [level,setLevel]=useState<Level>('Intermediate'); const [query,setQuery]=useState(''); const [picker,setPicker]=useState<'enemy'|'player'|null>(null);
 const [favs,setFavs]=useState<string[]>(()=>JSON.parse(localStorage.getItem('jjs-favs')||'[]')); const [problem,setProblem]=useState('keeping me at range');
 useEffect(()=>localStorage.setItem('jjs-favs',JSON.stringify(favs)),[favs]);
 const go=(c:Character,mode:View='character')=>{setEnemy(c);setView(mode);setPicker(null);scrollTo(0,0)};
 const results=useMemo(()=>{const q=query.toLowerCase().trim(); if(!q)return[]; return [...characters.filter(c=>[c.displayName,c.gameName,...c.aliases].some(x=>x.toLowerCase().includes(q)||q.includes(x.toLowerCase()))).map(x=>({kind:'character' as const,item:x})),...moves.filter(m=>m.moveName.toLowerCase().includes(q)||q.includes(m.moveName.toLowerCase())).map(x=>({kind:'move' as const,item:x}))].slice(0,8)},[query]);
 return <div className="app">
  <header><button className="brand" onClick={()=>setView('home')}><span className="brandmark">対</span><span>COUNTER<span>PLAY</span></span></button><div className="head-actions"><button className="icon-btn" onClick={()=>setView('moves')} aria-label="Search"><Search size={20}/></button><button className="avatar" onClick={()=>setView('mechanics')}>?</button></div></header>
  {view==='home'&&<Home go={go} setPicker={setPicker} query={query} setQuery={setQuery} results={results} player={player} favs={favs} />}
  {view==='character'&&enemy&&<Guide c={enemy} level={level} setLevel={setLevel} favs={favs} setFavs={setFavs} fight={()=>setView('fight')} matchup={()=>setPicker('player')} problem={problem} setProblem={setProblem}/>} 
  {view==='fight'&&enemy&&<Fight c={enemy} back={()=>setView('character')} setEnemy={setEnemy}/>} 
  {view==='moves'&&<MoveSearch query={query} setQuery={setQuery} go={go}/>} 
  {view==='matchup'&&enemy&&player&&<Matchup player={player} enemy={enemy}/>} 
  {view==='mechanics'&&<Mechanics/>}
  {picker&&<Picker title={picker==='enemy'?"Who are you fighting?":"Who are you playing?"} close={()=>setPicker(null)} choose={c=>{if(picker==='enemy')go(c);else{setPlayer(c);setPicker(null);setView('matchup')}}}/>} 
  <nav><button className={view==='home'?'active':''} onClick={()=>setView('home')}><Crosshair/>Counter</button><button className={view==='moves'?'active':''} onClick={()=>setView('moves')}><Search/>Moves</button><button className={view==='matchup'?'active':''} onClick={()=>setPicker('player')}><Swords/>Matchup</button><button className={view==='mechanics'?'active':''} onClick={()=>setView('mechanics')}><Shield/>Learn</button></nav>
 </div>
}

function Home({go,setPicker,query,setQuery,results,player,favs}:{go:(c:Character,v?:View)=>void,setPicker:(x:'enemy'|'player')=>void,query:string,setQuery:(x:string)=>void,results:any[],player:Character|null,favs:string[]}){
 const rec=characters.filter(c=>favs.includes(c.id));
 return <main className="home"><section className="hero"><div className="eyebrow"><span/>LIVE GUIDE · V1.82</div><h1>Stop guessing.<br/><em>Start countering.</em></h1><p>Choose who’s giving you trouble. Get the answer before the next round starts.</p><button className="losing" onClick={()=>setPicker('enemy')}><span><small>I’M LOSING TO...</small>Choose enemy character</span><Crosshair size={30}/></button><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ‘blue’, ‘yuji vs todo’..."/>{query&&<button onClick={()=>setQuery('')}><X/></button>} {results.length>0&&<div className="results">{results.map((r:any)=><button key={r.item.id} onClick={()=>r.kind==='character'?go(r.item):go(characters.find(c=>c.id===r.item.characterId)!,'moves')}><span>{r.kind==='move'?'MOVE':'FIGHTER'}</span>{r.kind==='move'?r.item.moveName:r.item.displayName}<ChevronRight/></button>)}</div>}</div></section>
 <section className="section"><div className="section-head"><div><span className="kicker">QUICK ACCESS</span><h2>{rec.length?'Your saved counters':'Most searched counters'}</h2></div><button onClick={()=>setPicker('enemy')}>See all</button></div><div className="card-row">{(rec.length?rec:characters.slice(0,5)).map(c=><CharacterCard key={c.id} c={c} go={go}/>)}</div></section>
 <section className="coach"><div className="coach-icon"><Zap/></div><div><span className="kicker">FIGHT IQ</span><h3>Don’t evasive the first knockdown.</h3><p>Spend it when the opponent has committed an extension—or when your cancel can punish their recovery.</p></div></section>
 <section className="section compact"><span className="kicker">FIGHTING AS</span><button className="select-line" onClick={()=>setPicker('player')}><span>{player?.initials||'+'}</span><div><b>{player?.displayName||'Set your main'}</b><small>Get character-specific counter plans</small></div><ChevronRight/></button></section></main>
}

function CharacterCard({c,go}:{c:Character,go:(c:Character)=>void}){return <button className="char-card" style={{'--accent':c.accent} as any} onClick={()=>go(c)}><div className="char-art"><span>{c.initials}</span><i/></div><small>{c.gameName}</small><b>{c.displayName}</b><div>{c.range} range <ChevronRight/></div></button>}

function Guide({c,level,setLevel,favs,setFavs,fight,matchup,problem,setProblem}:{c:Character,level:Level,setLevel:(x:Level)=>void,favs:string[],setFavs:(x:string[])=>void,fight:()=>void,matchup:()=>void,problem:string,setProblem:(x:string)=>void}){
 const cmoves=moves.filter(m=>m.characterId===c.id), saved=favs.includes(c.id); const toggle=()=>setFavs(saved?favs.filter(x=>x!==c.id):[...favs,c.id]);
 return <main className="guide"><section className="identity" style={{'--accent':c.accent} as any}><div className="identity-actions"><span className="pill">{c.access.replace('-',' ')}</span><button onClick={toggle}>{saved?<Heart fill="currentColor"/>:<Heart/>}</button></div><div className="monogram">{c.initials}</div><span className="kicker">{c.gameName}</span><h1>{c.displayName}</h1><div className="tags">{c.playstyle.map(x=><span key={x}>{x}</span>)}<span>{c.range} fight</span></div></section>
 <div className="tabbar"><button className="active">Counter</button><button onClick={()=>document.getElementById('moves')?.scrollIntoView()}>Moves</button><button onClick={matchup}>Matchup</button><button onClick={()=>document.getElementById('awakening')?.scrollIntoView()}>Awakening</button></div>
 <section className="quick"><div className="quick-top"><span className="kicker">READ THIS IN 5 SECONDS</span><button onClick={fight}><Zap/> Fight now</button></div><h2>Quick counter</h2><Action marker="RNG" label="FIGHT AT" value={c.range}/><Action marker="WEAK" label="BIGGEST WEAKNESS" value={c.biggestWeakness}/><Action marker="BLK" label="BLOCK" value={c.block}/><Action marker="DGE" label="DODGE" value={c.dodge}/><Action marker="EVA" label="SAVE EVASIVE FOR" value={c.evasive}/><Action marker="PUN" label="PUNISH" value={c.punish}/></section>
 <section className="content"><div className="level"><span>Advice level</span>{(['Beginner','Intermediate','Advanced'] as Level[]).map(x=><button className={level===x?'active':''} onClick={()=>setLevel(x)} key={x}>{x}</button>)}</div><span className="kicker">TOP 3 THINGS TO KNOW</span>{c.topTips.map((t,i)=><article className="number-tip" key={t.title}><b>0{i+1}</b><div><h3>{t.title}</h3><p>{level==='Beginner'?t.body.split(';')[0]+'.':t.body}</p><details><summary>Why does this work?</summary><p>{t.confidence} guidance, supported by the linked mechanics and community references.</p></details></div></article>)}
 <h2 className="title">Where the matchup breaks</h2>{c.weaknesses.map(t=><article className="weak" key={t.title}><CircleAlert/><div><h3>{t.title}</h3><p>{t.body}</p><span>{t.confidence} strategy</span></div></article>)}
 <section id="moves"><span className="kicker">MOVE-BY-MOVE</span><h2 className="title">When you see it</h2>{cmoves.length?cmoves.map(m=><MoveRow key={m.id} m={m}/>):<div className="notice"><CircleAlert/><p><b>Detailed move verification in progress.</b><br/>This changing or less-documented kit currently uses the quick plan above. No move interactions are being guessed.</p></div>}</section>
 <h2 className="title">What they usually try</h2>{c.patterns.map(p=><article className="pattern" key={p.level}><span>{p.level}</span><h3>{p.theyTry}</h3><div><b>Your answer</b><p>{p.youDo}</p></div></article>)}
 <section className="trouble"><span className="kicker">TROUBLESHOOTER</span><h2>They keep…</h2><select value={problem} onChange={e=>setProblem(e.target.value)}>{Object.keys(c.trouble).map(x=><option key={x}>{x}</option>)}</select><p>{c.trouble[problem]}</p></section>
 <section className="awake" id="awakening"><Sparkles/><span className="kicker">THEY JUST AWAKENED</span><h2>Change the plan.</h2><p>{c.awakening}</p><button onClick={fight}>Open emergency view <ChevronRight/></button></section>
 <Evidence ids={[...new Set(c.topTips.flatMap(t=>t.sourceIds))]}/></section></main>
}

function Action({marker,label,value}:{marker:string,label:string,value:string}){return <div className="action"><span>{marker}</span><div><small>{label}</small><p>{value}</p></div></div>}
function MoveRow({m}:{m:MoveCounter}){return <details className="move"><summary><span>{actionMark[m.recommendedResponse]||'ACT'}</span><div><b>{m.moveName}</b><small>{m.form} · {m.confidence}</small></div><i>{m.recommendedResponse.replace(/([A-Z])/g,' $1')}</i><ChevronRight/></summary><div className="move-body"><p><b>When you see it:</b> {m.tell}</p><p><b>Do this:</b> {m.counterStrategy}</p><p className="dont"><b>Don’t:</b> {m.avoid}</p>{m.evasiveTiming&&<p><b>Evasive:</b> {m.evasiveTiming}</p>}<div className="facts"><span>Block: {String(m.blockable)}</span><span>Guard break: {String(m.guardBreak)}</span><span>{m.attackType}</span></div></div></details>}

function Fight({c,back,setEnemy}:{c:Character,back:()=>void,setEnemy:(c:Character)=>void}){const idx=characters.indexOf(c),shift=(n:number)=>setEnemy(characters[(idx+n+characters.length)%characters.length]);return <main className="fight" style={{'--accent':c.accent} as any}><div className="fight-head"><button onClick={back}><ArrowLeft/></button><span>FIGHT NOW</span><button><Menu/></button></div><div className="fight-id"><span>{c.gameName}</span><h1>{c.displayName}</h1><p>Swipe the plan. Win the interaction.</p></div><div className="fight-grid"><Action marker="RNG" label="FIGHT AT" value={c.range}/><Action marker="BLK" label="BLOCK" value={c.block}/><Action marker="DGE" label="DODGE" value={c.dodge}/><Action marker="EVA" label="EVASIVE" value={c.evasive}/><Action marker="PUN" label="PUNISH" value={c.punish}/><Action marker="WARN" label="WATCH FOR" value={c.biggestWeakness}/></div><div className="fight-awake"><Sparkles/><div><small>IF THEY AWAKEN</small><p>{c.awakening}</p></div></div><div className="swipe"><button onClick={()=>shift(-1)}>‹</button><span>Tap arrows to change fighter</span><button onClick={()=>shift(1)}>›</button></div></main>}

function MoveSearch({query,setQuery,go}:{query:string,setQuery:(x:string)=>void,go:(c:Character,v?:View)=>void}){const filtered=moves.filter(m=>m.moveName.toLowerCase().includes(query.toLowerCase()));return <main className="page"><span className="kicker">MOVE LAB</span><h1>Beat the move,<br/>not the name.</h1><div className="search sticky"><Search/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try ‘Piercing Blood’..."/></div><p className="muted">{filtered.length} verified or labeled results</p>{filtered.map(m=><div key={m.id} onClick={()=>go(characters.find(c=>c.id===m.characterId)!)}><MoveRow m={m}/></div>)}</main>}

function Matchup({player,enemy}:{player:Character,enemy:Character}){return <main className="page matchup"><span className="kicker">MATCHUP PLAN</span><h1>{player.displayName} <em>vs</em> {enemy.displayName}</h1><div className="versus"><div style={{background:player.accent}}>{player.initials}</div><Swords/><div style={{background:enemy.accent}}>{enemy.initials}</div></div><Plan n="01" title="Neutral" text={`Use ${player.playstyle[0]} tools to stay ${enemy.range.toLowerCase()}. ${enemy.dodge}`}/><Plan n="02" title="What you’re baiting" text={enemy.punish}/><Plan n="03" title="When you get in" text={`Convert fully—${enemy.biggestWeakness}`}/><Plan n="04" title="Your dangerous mistake" text={`Do not autopilot ${player.playstyle[0]} pressure into their prepared defensive answer.`}/><Plan n="05" title="Evasive" text={enemy.evasive}/><div className="notice"><CircleAlert/><p>This matchup is assembled from both character layers. Unique authored overrides are not yet verified for every pair.</p></div></main>}
function Plan({n,title,text}:{n:string,title:string,text:string}){return <article className="plan"><b>{n}</b><div><h2>{title}</h2><p>{text}</p></div></article>}

function Mechanics(){return <main className="page"><span className="kicker">UNIVERSAL MECHANICS</span><h1>Know what your<br/>counter can catch.</h1><p className="lead">“Countering” a game plan is different from activating a Counter ability. Attack class decides the interaction.</p><div className="matrix-wrap"><table><thead><tr><th>Ability</th><th>Melee</th><th>Bullet</th><th>Swarm</th><th>Explosion</th><th>Domain</th></tr></thead><tbody>{counterMatrix.map(r=><tr key={r.name}>{Object.values(r).map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div><article className="mechanic-card"><Zap/><div><h2>Ragdoll cancel / evasive</h2><p>Side-dash while ragdolled for a quickstep, stand-up, and roughly one second of invulnerability. The meter refills through damage dealt/taken; downslams and wake-up pressure also add charge.</p></div></article><article className="mechanic-card"><Shield/><div><h2>Blocking</h2><p>Block mainly protects the front—generally under a 180° angle. Some attacks bypass it, need a perfect block, deal chip, or become stronger when blocked.</p></div></article><Evidence ids={['mechanics']}/></main>}

function Evidence({ids}:{ids:string[]}){return <details className="evidence"><summary><Bookmark/> Evidence & freshness <ChevronRight/></summary><div><p>Checked September 29, 2026 · V1.82. Mechanics and strategy are labeled separately; community guidance is not presented as frame-perfect fact.</p>{sources.filter(s=>ids.includes(s.id)).map(s=><a key={s.id} href={s.url} target="_blank">{s.title}<ExternalLink/></a>)}</div></details>}

function Picker({title,close,choose}:{title:string,close:()=>void,choose:(c:Character)=>void}){const [q,setQ]=useState(''); const list=characters.filter(c=>(c.displayName+c.gameName).toLowerCase().includes(q.toLowerCase()));return <div className="sheet-bg" onClick={close}><section className="sheet" onClick={e=>e.stopPropagation()}><div className="grab"/><div className="sheet-title"><div><span className="kicker">SELECT MATCHUP</span><h2>{title}</h2></div><button onClick={close}><X/></button></div><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search roster..."/></div><div className="roster">{list.map(c=><button key={c.id} onClick={()=>choose(c)} style={{'--accent':c.accent} as any}><span>{c.initials}</span><div><b>{c.displayName}</b><small>{c.gameName} · {c.access.replace('-',' ')}</small></div><ChevronRight/></button>)}</div></section></div>}
export default App;
